// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOP-keTRxYDWqRrzePTSA9vGTJv9EMUzY',
    appId: '1:195009943245:web:6842f93a3faa0f3823fb84',
    messagingSenderId: '195009943245',
    projectId: 'greencloud-8e08d',
    authDomain: 'greencloud-8e08d.firebaseapp.com',
    databaseURL: 'https://greencloud-8e08d-default-rtdb.firebaseio.com',
    storageBucket: 'greencloud-8e08d.firebasestorage.app',
    measurementId: 'G-9CCFSL3Z74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wUT3pOaN0fJdeJfYNrG-JbbHO9ddul0',
    appId: '1:195009943245:android:ce419de456f9f5d223fb84',
    messagingSenderId: '195009943245',
    projectId: 'greencloud-8e08d',
    databaseURL: 'https://greencloud-8e08d-default-rtdb.firebaseio.com',
    storageBucket: 'greencloud-8e08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_gp6f-5gnH-RXtEISjSAjxYIk3oX3jc',
    appId: '1:195009943245:ios:f179ca877dc37ab423fb84',
    messagingSenderId: '195009943245',
    projectId: 'greencloud-8e08d',
    databaseURL: 'https://greencloud-8e08d-default-rtdb.firebaseio.com',
    storageBucket: 'greencloud-8e08d.firebasestorage.app',
    iosClientId: '195009943245-ocdphk8quf9h5gec8e1bu2lqt69sjjvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_gp6f-5gnH-RXtEISjSAjxYIk3oX3jc',
    appId: '1:195009943245:ios:f179ca877dc37ab423fb84',
    messagingSenderId: '195009943245',
    projectId: 'greencloud-8e08d',
    databaseURL: 'https://greencloud-8e08d-default-rtdb.firebaseio.com',
    storageBucket: 'greencloud-8e08d.firebasestorage.app',
    iosClientId: '195009943245-ocdphk8quf9h5gec8e1bu2lqt69sjjvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOP-keTRxYDWqRrzePTSA9vGTJv9EMUzY',
    appId: '1:195009943245:web:f5bbcfd6c6efd00423fb84',
    messagingSenderId: '195009943245',
    projectId: 'greencloud-8e08d',
    authDomain: 'greencloud-8e08d.firebaseapp.com',
    databaseURL: 'https://greencloud-8e08d-default-rtdb.firebaseio.com',
    storageBucket: 'greencloud-8e08d.firebasestorage.app',
    measurementId: 'G-4V025DYVTJ',
  );

}